#Below are the substitutions for SF's yaml
# "TopicArn":"${dev-kna-sfsns-nitya-intern-arn}" for sns[all]
# "FunctionName": "${OrchRowFetchLambdaNitya}", for rowfetch lambda
# "FunctionName": "${OrchPreProcLambdaNitya}", for docprocessor lambda
# "JobName": "dev_kna_icebergglue_nitya_intern", -> replaced by
# "JobName": "${orch-iceberg-glue-nitya-intern}", 
AWSTemplateFormatVersion: 2010-09-09
Description: Lambda Flexible to be used across
Parameters:
  SNSArn-nitya:
    Type: String
    Default: arn:aws:sns:ap-southeast-2:797671034147:testtop
  RowfetchLambdaArn-nitya:
    Type: String
    Default: arn:aws:lambda:ap-southeast-2:797671034147:function:dev_kna_rowfetch_nitya_intern
  PreProcLambdaArn-nitya:
    Type:String
    Default: arn:aws:lambda:ap-southeast-2:797671034147:function:dev_kna_processor_nitya_intern
  IcebergGlueArn-nitya:
    Type: String
    Default: arn:aws:glue:ap-southeast-2:797671034147:job:dev-kna-orch-icebergglue-nitya-intern
Resources:
  orchstatemachine-nitya:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: dev-orch-cfnsf-nitya-intern
      DefinitionS3Location:
        Bucket: klg-nga-dev-kna-raw-intrnl
        Key: intern_2025/nitya/StepFormationYAML/dev_orch_intern_t7procsf_nitya.yaml
      DefinitionSubstitutions:
        dev-kna-sfsns-nitya-intern-arn: !Ref SNSArn-nitya 
        OrchRowFetchLambdaNitya: !Ref RowfetchLambdaArn-nitya
        OrchPreProcLambdaNitya: !Ref PreProcLambdaArn-nitya
        orch-iceberg-glue-nitya-intern: !Ref IcebergGlueArn-nitya
      RoleArn: arn:aws:iam::797671034147:role/ELT-GITHUBROLE-NITYA
      
  
