#Below are the substitutions for SF's yaml
# "TopicArn":"${dev-kna-sfsns-nitya-intern-arn}" for sns[all]
# "FunctionName": "${OrchRowFetchLambdaNitya}", for rowfetch lambda
# "FunctionName": "${OrchPreProcLambdaNitya}", for docprocessor lambda
# "JobName": "dev_kna_icebergglue_nitya_intern", -> replaced by
# "JobName": "${orch-iceberg-glue-nitya-intern}", 
AWSTemplateFormatVersion: 2010-09-09
Description: Lambda Flexible to be used across
Parameters:
  SNSArnnitya:
    Type: String
    Default: arn:aws:sns:ap-southeast-2:797671034147:testtop
  RowfetchLambdaArnnitya:
    Type: String
    Default: arn:aws:lambda:ap-southeast-2:797671034147:function:dev_kna_rowfetch_nitya_intern
  PreProcLambdaArnnitya:
    Type: String
    Default: arn:aws:lambda:ap-southeast-2:797671034147:function:dev_kna_processor_nitya_intern
  IcebergGlueArnnitya:
    Type: String
    Default: arn:aws:glue:ap-southeast-2:797671034147:job:dev-kna-orch-icebergglue-nitya-intern
Resources:
  orchstatemachinenitya:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: dev-orch-cfnsf-nitya-intern
      DefinitionS3Location:
        Bucket: klg-nga-dev-kna-raw-intrnl
        Key: intern_2025/nitya/StepFormationYAML/dev_orch_intern_t7procsf_nitya.yaml
      DefinitionSubstitutions:
        dev-kna-sfsns-nitya-intern-arn: !Ref SNSArnnitya 
        OrchRowFetchLambdaNitya: !Ref RowfetchLambdaArnnitya
        OrchPreProcLambdaNitya: !Ref PreProcLambdaArnnitya
        orch-iceberg-glue-nitya-intern: !Ref IcebergGlueArnnitya
      RoleArn: arn:aws:iam::797671034147:role/ELT-GITHUBROLE-NITYA
      
  
