name: devops-elt-nitya-intern
on:
  push: 
    branches:
      - main
jobs:
  cloudformation-validation-nitya:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout from github repo
        uses: actions/checkout@v4

      - name: Setup cloudformation linter
        uses: scottbrenner/cfn-lint-action@v2

      - name: Validate cloudformation templates using linter
        run: |
          cfn-lint --version
          cfn-lint interns/nitya/infrastructure/eltinfra-lambda-nitya-intern.yaml
          cfn-lint interns/nitya/infrastructure/eltinfra-sqs-nitya-intern.yaml
          cfn-lint interns/nitya/infrastructure/orch-iceberg-glue-nitya-intern.yaml
          cfn-lint interns/nitya/infrastructure/orch-sf-cfn-nitya-intern.yaml
  dev-kna-etl-pipeline-run:
    runs-on: ubuntu-latest
    needs: cloudformation-validation-nitya
    steps:
      - name: Code checkout from github repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_SECRET_REGION }}

      - name: Upload glue script to S3
        run: |
          aws s3 cp interns/nitya/scripts/glue/dev_kna_icebergglue_nitya_intern.py \
                    s3://klg-nga-dev-kna-raw-intrnl-nitya/intern_2025/nitya/Glue_Scripts/ --sse AES256
      - name: Upload stepfunction script to S3
        run: |
          aws s3 cp interns/nitya/statemachines/dev_orch_intern_t7procsf_nitya.yaml \
                    s3://klg-nga-dev-kna-raw-intrnl-nitya/intern_2025/nitya/StepFormationYAML/ --sse AES256
                    
      # - name: Cloudformation for SNS Data Fetch
      #   uses: aws-actions/aws-cloudformation-github-deploy@v1
      #   with:
      #     name: dev-kna-sfsns-nitya-intern
      #     template: interns/nitya/infrastructure/orch-sf-sns-nitya-intern.yaml
      #     no-fail-on-empty-changeset:  "1"

      - name: CloudFormation for IcebergTable Glue
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: dev-kna-orch-icebergglue-nitya-intern
          template: interns/nitya/infrastructure/orch-iceberg-glue-nitya-intern.yaml
          parameter-overrides: SecretKey=testval
          no-fail-on-empty-changeset:  "1"
      - name: Cloudformation for StepFunction
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: dev-kna-sf-cfn-nitya-intern
          template: interns/nitya/infrastructure/orch-sf-cfn-nitya-intern.yaml
          no-fail-on-empty-changeset:  "1"

      - name: Cloudformation for all lambda and layers
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: dev-kna-etlinfralmdcf-nitya-intern
          template: interns/nitya/infrastructure/eltinfra-lambda-nitya-intern.yaml
            SecretKey=testvall
            SFArnnitya=dev-kna-orch-icebergglue-nitya-intern
          no-fail-on-empty-changeset:  "1"
  
