name: devops-elt-nitya-intern
on:
  pull_request:
    types:
      - closed
    branches:
      - interns-main
jobs:
  cloudformation-validation-nitya:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout from github repo
        uses: actions/checkout@v4

      - name: Setup cloudformation linter
        uses: scottbrenner/cfn-lint-action@v2

      - name: Validate cloudformation templates using linter
        run: |
          cfn-lint --version
          cfn-lint interns/nitya/infrastructure/eltinfra-lambda-nitya-intern.yaml
          cfn-lint interns/nitya/infrastructure/eltinfra-sqs-nitya-intern.yaml
          cfn-lint interns/nitya/infrastructure/orch-iceberg-glue-nitya-intern.yaml
          cfn-lint interns/nitya/infrastructure/orch-sf-cfn-nitya-intern.yaml
  dev-kna-etl-pipeline-run:
    runs-on: ubuntu-latest
    environment: dev-kna
    steps:
      - name: Code checkout from github repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_SECRET_REGION }}
      - name: Zip lambda script that extract metadata and load
        run: |
          mkdir -p interns/nitya/scripts/lambda/build
          zip  interns/nitya/scripts/lambda/build/dev_kna_extractload_nitya_intern.zip \
                interns/nitya/scripts/lambda/dev_kna_extractload_nitya_intern.py
      - name: Zip lambda script that fetches row
        run: |
          mkdir -p interns/nitya/scripts/lambda/build
          zip  interns/nitya/scripts/lambda/build/dev_kna_rowfetch_nitya_intern.zip \
                interns/nitya/scripts/lambda/dev_kna_rowfetch_nitya_intern.py
      - name: Zip lambda script that performs pre-processing
        run: |
          mkdir -p interns/nitya/scripts/lambda/build
          zip  interns/nitya/scripts/lambda/build/dev_kna_processor_nitya_intern.zip \
                interns/nitya/scripts/lambda/dev_kna_processor_nitya_intern.py
      - name: Zip psycopg2 layer
        run: |
          cd interns/nitya/scripts/lambda/layers/psycopg2-nitya
          zip -r ../lambdazip-nitya/psycopg2-nitya.zip python
      - name: Zip preproc layer
        run: |
          cd interns/nitya/scripts/lambda/layers/preproc-nitya
          zip -r ../lambdazip-nitya/preproc-nitya.zip python 
      - name: Zip lambda script that performs sf trigger
        run: |
          mkdir -p interns/nitya/scripts/lambda/build
          zip  interns/nitya/scripts/lambda/build/dev_kna_sftrig_nitya_intern.zip \
                interns/nitya/scripts/lambda/dev_kna_sftrig_nitya_intern.py
      - name: Upload lambda scripts to S3
        run: |
          aws s3 cp interns/nitya/scripts/lambda/build/dev_kna_extractload_nitya_intern.zip \
                    s3://klg-nga-dev-kna-raw-intrnl/intern_2025/nitya/Lambda_Scripts/
          aws s3 cp interns/nitya/scripts/lambda/build/dev_kna_rowfetch_nitya_intern.zip \
                    s3://klg-nga-dev-kna-raw-intrnl/intern_2025/nitya/Lambda_Scripts/
          aws s3 cp interns/nitya/scripts/lambda/build/dev_kna_processor_nitya_intern.zip \
                    s3://klg-nga-dev-kna-raw-intrnl/intern_2025/nitya/Lambda_Scripts/  
          aws s3 cp interns/nitya/scripts/lambda/build/dev_kna_sftrig_nitya_intern.zip \
                    s3://klg-nga-dev-kna-raw-intrnl/intern_2025/nitya/Lambda_Scripts/  
      - name: Upload lambda layers to S3
        run: |
          aws s3 cp interns/nitya/scripts/lambda/layers/lambdazip-nitya/psycopg2-nitya.zip \
                    s3://klg-nga-dev-kna-raw-intrnl/intern_2025/nitya/Lambda_Scripts/Layers/ 
          aws s3 cp interns/nitya/scripts/lambda/layers/lambdazip-nitya/preproc-nitya.zip \
                    s3://klg-nga-dev-kna-raw-intrnl/intern_2025/nitya/Lambda_Scripts/Layers/ 
      # - name: Create psycopg2 LambdaLayer
      #   uses: aws-actions/aws-cloudformation-github-deploy@v1
      #   with:
      #     name: dev-kna-psycopg2layer-nitya-intern
      #     template: interns/nitya/infrastructure/eltinfra-layercf-nitya-intern.yaml
      #     no-fail-on-empty-changeset: true
      #     role-arn: ${{secrets.CICD_EXECUTION_ROLE}}
      #     parameter-overrides: |
      #       LayerName: psycopg2-nitya
      #       Filekey: intern_2025/nitya/Lambda_Scripts/Layers/psycopg2-nitya.zip
      # - name: Create preproc LambdaLayer
      #   uses: aws-actions/aws-cloudformation-github-deploy@v1
      #   with:
      #     name: dev-kna-preproclayer-nitya-intern
      #     template: interns/nitya/infrastructure/eltinfra-layercf-nitya-intern.yaml
      #     no-fail-on-empty-changeset: true
      #     role-arn: ${{secrets.CICD_EXECUTION_ROLE}}
      #     parameter-overrides: |
      #       LayerName: preproc-nitya
      #       Filekey: intern_2025/nitya/Lambda_Scripts/Layers/preproc-nitya.zip
      - name: Cloudformation for SQS Data Fetch
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: dev-kna-eltinfrasqscf-nitya-intern
          template: interns/nitya/infrastructure/eltinfra-sqs-nitya-intern.yaml
          no-fail-on-empty-changeset: true

      - name: Cloudformation for all lambda and layers
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: dev-kna-etlinfralmdcf-nitya-intern
          template: interns/nitya/infrastructure/eltinfra-lambda-nitya-intern.yaml
          parameter-overrides: secret_key=${{secrets.SECRET_KEY_NAME}}
          no-fail-on-empty-changeset: true
       
        
    
