name: Action to upload incoming python glue file
on:
  push:
    branches:
      - main
    paths: 
      - Templates/GlueTemplates
jobs:
  deploy:
    runs-on: ubuntu-latest #considering OS of AWS
    environment:
      name: Test
    steps:
      - name: RunCheckout 
        uses: actions/checkout@v4
        #credentials for AWS put in here
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_SECRET_REGION }}
      - name: upload new python files to glue path
        run: |
          aws s3 sync Scripts/GlueScripts/ s3://cloudformation-template-nitya/LambdaPythonScripts/
